export const ServiceThumb = [
  {
    id: 1,
    title: '소설 패키지',
    link: '/service/novel/intro',
    detail: '/detail/novel',
    imagePng: 'images/01.png',
    imageWebp: 'images/01.webp',
    discription: '웹소설 창작의 시작',
    keyName: 'novel_intro',
  },
  {
    id: 2,
    title: '블로그 글쓰기',
    link: '/service/blog/idea',
    detail: '/detail/blog',
    imagePng: 'images/02.png',
    imageWebp: 'images/02.webp',
    discription: '매력적인 블로그 콘텐츠',
    keyName: 'blog_idea',
  },
  {
    id: 3,
    title: '동화 쓰기',
    link: '/service/fairy/intro',
    detail: '/detail/fairy',
    imagePng: 'images/03.png',
    imageWebp: 'images/03.webp',
    discription: '함께 만드는 동화',
    keyName: 'fairy_intro',
  },
  {
    id: 4,
    title: '첫문장 자판기',
    link: '/service/firstsentence',
    detail: '/detail/firstsentence',
    imagePng: 'images/04.png',
    imageWebp: 'images/04.webp',
    discription: '독자를 사로잡는 첫 문장',
    keyName: 'first_sentence',
  },
  {
    id: 5,
    title: '시 가사 쓰기',
    link: '/service/lyrics',
    detail: '/detail/lyrics',
    imagePng: 'images/05.png',
    imageWebp: 'images/05.webp',
    discription: '자유로운 창작의 시와 가사',
    keyName: 'lyrics',
  },
  {
    id: 6,
    title: '비즈니스 아이디어',
    link: '/service/business',
    detail: '/detail/business',
    imagePng: 'images/06.png',
    imageWebp: 'images/06.webp',
    discription: '창의적인 비즈니스 제안',
    keyName: 'business',
  },
  {
    id: 7,
    title: 'MBTI 연애편지',
    link: '/service/mbti_loveletter',
    detail: '/detail/mbti_loveletter',
    imagePng: 'images/07.png',
    imageWebp: 'images/07.webp',
    discription: 'MBTI로 표현하는 사랑의 감정',
    keyName: 'mbti_loveletter',
  },
  {
    id: 8,
    title: '찬반 논거',
    link: '/service/discussion',
    detail: '/detail/discussion',
    imagePng: 'images/08.png',
    imageWebp: 'images/08.webp',
    discription: '균형 잡힌 논리 전개',
    keyName: 'discussion',
  },

  {
    id: 9,
    title: '글감 찾기 질문카드',
    link: '/service/material',
    detail: '/detail/material',
    imagePng: 'images/09.png',
    imageWebp: 'images/09.webp',
    discription: '파일상에서 영감을 발견하세요',
    keyName: 'material',
  },
  {
    id: 10,
    title: '이야기 재료 찾기',
    link: '/service/storysrc',
    detail: '/detail/storysrc',
    imagePng: 'images/10.png',
    imageWebp: 'images/10.webp',
    discription: '이야기의 시작을 찾아서',
    keyName: 'storysrc',
  },
  {
    id: 11,
    title: '대입 자소서 자동 완성',
    link: '/service/coverletter',
    detail: '/detail/coverletter',
    imagePng: 'images/11.png',
    imageWebp: 'images/11.webp',
    discription: '간편한 대입 자소서 작성',
    keyName: 'coverletter',
  },

  {
    id: 13,
    title: '뉴스레터 에디터',
    link: '/service/letter_edit',
    detail: '/detail/letter_edit',
    imagePng: 'images/13.png',
    imageWebp: 'images/13.webp',
    discription: '뉴스레터 쉽게 만들기',
    keyName: 'newsletter',
  },
  {
    id: 14,
    title: `상품 소개문구 & 상품후기`,
    link: '/service/product_intro',
    detail: '/detail/product',
    imagePng: 'images/14.png',
    imageWebp: 'images/14.webp',
    discription: '인상적인 상품 설명과 후기',
    keyName: 'product_intro',
  },
  {
    id: 15,
    title: `판타지 세계관 생성`,
    link: '/service/fantasy',
    detail: '/detail/fantasy',
    imagePng: 'images/15.png',
    imageWebp: 'images/15.webp',
    discription: '쉬운 판타지 세계 창조',
    keyName: 'fantasy',
  },
  {
    id: 16,
    title: `뒷문장 자판기`,
    link: '/service/nextsentence',
    detail: '/detail/nextsentence',
    imagePng: 'images/16.png',
    imageWebp: 'images/16.webp',
    discription: '문장 이어쓰기의 도움',
    keyName: 'next_sentence',
  },
  {
    id: 17,
    title: `이메일 작성`,
    link: '/service/email',
    detail: '/detail/email',
    imagePng: 'images/17.png',
    imageWebp: 'images/17.webp',
    discription: '전문적인 이메일 스킬',
    keyName: 'email',
  },
  {
    id: 18,
    title: `취업 자소서 작성`,
    link: '/service/resume',
    detail: '/detail/resume',
    imagePng: 'images/18.png',
    imageWebp: 'images/18.webp',
    discription: '취업을 위한 자소서 강화',
    keyName: 'resume',
  },
  {
    id: 19,
    title: `일기 쓰기`,
    link: '/service/diary',
    detail: '/detail/diary',
    imagePng: 'images/19.png',
    imageWebp: 'images/19.webp',
    discription: '일상을 기록하는 즐거움',
    keyName: 'diary',
  },
];
